package admin

import (
	"crypto/rand"
	"encoding/hex"
	"net/http"

	"github.com/onaonbir/Cloodsy-S3/httpx"
	"golang.org/x/crypto/bcrypt"
)

func generatePassword() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func (h *Handler) handleListAdmins(w http.ResponseWriter, r *http.Request) {
	admins, err := h.DB.ListAdmins()
	if err != nil {
		h.Logger.Error("list admins error", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	result := make([]map[string]interface{}, 0, len(admins))
	for _, a := range admins {
		result = append(result, map[string]interface{}{
			"id":         a.ID,
			"username":   a.Username,
			"created_at": a.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"),
		})
	}

	writeJSON(w, http.StatusOK, map[string]interface{}{"admins": result})
}

func (h *Handler) handleCreateAdmin(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Username string `json:"username"`
		Password string `json:"password"` // optional — if empty, auto-generate
	}
	if !decodeJSON(w, r, &req, false) {
		return
	}
	if req.Username == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "username is required"})
		return
	}
	if len(req.Username) > maxUsernameLen {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "username too long"})
		return
	}
	if req.Username != httpx.SanitizeLog(req.Username) {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "username contains control characters"})
		return
	}

	existing, err := h.DB.GetAdmin(req.Username)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}
	if existing != nil {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "admin already exists"})
		return
	}

	password := req.Password
	autoGenerated := false
	if password == "" {
		password, err = generatePassword()
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
			return
		}
		autoGenerated = true
	} else if msg := validatePassword(password); msg != "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": msg})
		return
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(password), 12)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	admin, err := h.DB.CreateAdmin(req.Username, string(hash))
	if err != nil {
		h.Logger.Error("create admin error", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	h.Logger.Info("admin created via API", "username", httpx.SanitizeLog(req.Username))
	writeJSON(w, http.StatusCreated, map[string]interface{}{
		"id":             admin.ID,
		"username":       admin.Username,
		"password":       password,
		"auto_generated": autoGenerated,
		"created_at":     admin.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"),
	})
}

func (h *Handler) handleDeleteAdmin(w http.ResponseWriter, r *http.Request, username, currentUser string) {
	if username == currentUser {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "cannot delete your own account"})
		return
	}

	existing, err := h.DB.GetAdmin(username)
	if err != nil || existing == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "admin not found"})
		return
	}

	// Prevent deleting the last admin
	count, err := h.DB.CountAdmins()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}
	if count <= 1 {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "cannot delete the last admin"})
		return
	}

	if err := h.DB.DeleteAdmin(username); err != nil {
		h.Logger.Error("delete admin error", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	// A deleted account must not keep working through an old token.
	revoked := h.revokeSessions(username)

	h.Logger.Info("admin deleted via API", "username", httpx.SanitizeLog(username), "by", httpx.SanitizeLog(currentUser), "sessions_revoked", revoked)
	writeJSON(w, http.StatusOK, map[string]string{"message": "admin deleted"})
}

func (h *Handler) handleUpdateAdminPassword(w http.ResponseWriter, r *http.Request, username string) {
	existing, err := h.DB.GetAdmin(username)
	if err != nil || existing == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "admin not found"})
		return
	}

	var req struct {
		Password string `json:"password"` // optional — if empty, auto-generate
	}
	// An entirely empty body means "generate one for me"; a malformed body
	// must never silently rotate the password to a random value.
	if !decodeJSON(w, r, &req, true) {
		return
	}

	password := req.Password
	autoGenerated := false
	if password == "" {
		password, err = generatePassword()
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
			return
		}
		autoGenerated = true
	} else if msg := validatePassword(password); msg != "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": msg})
		return
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(password), 12)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	if err := h.DB.UpdateAdminPassword(username, string(hash)); err != nil {
		h.Logger.Error("update admin password error", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal error"})
		return
	}

	// Existing sessions were established with the old secret; drop them.
	revoked := h.revokeSessions(username)

	h.Logger.Info("admin password updated via API", "username", httpx.SanitizeLog(username), "sessions_revoked", revoked)
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"username":       username,
		"password":       password,
		"auto_generated": autoGenerated,
		"message":        "password updated",
	})
}
